-------VALIDA SI EL REGISTRO EXISTE Y ESTA PENDIENTE (SI NO TIRA LA EXCEPCION)
PERFORM * FROM compras_orden_cabecera WHERE id_corden = cid_corden AND estado = 'PENDIENTE';
    IF NOT FOUND THEN 
        RAISE EXCEPTION 'A ESTE MOVIMIENTO NO SE PUEDE ELIMINAR O NO EXISTE';
    END IF;

-------VALIDA SI EL REGISTRO YA HA SIDO REGISTRADO
PERFORM * FROM compras_orden_detalle WHERE id_corden = cid_corden AND id_item = cid_item;
    IF FOUND THEN 
        RAISE EXCEPTION 'ESTE ITEM YA HA SIDO REGISTRADO';
    END IF;

-------VALIDA SI EXISTE MOVIMIENTO PEDIENTE
PERFORM * FROM compras_orden_cabecera WHERE id_sucursal = xid_sucursal AND estado = 'PENDIENTE';
    	IF FOUND THEN
    	RAISE EXCEPTION 'EXISTEN PRESUPUESTO PENDIENTES DE CONFIRMACIÓN';
    	END IF;

------VALIDA SI EL MOVIMIENTO POSEE DETALLES PARA LA CONFIRMACION
PERFORM * FROM v_compras_presupuestos_consolidacion vcpc WHERE id_cpre = cid_cpre;     
       IF NOT FOUND THEN
            RAISE EXCEPTION 'ESTE PRESUPUESTO NO POSEE DETALLES CARGADOS';
        END IF;